Readme and documentation
uorocketry/hydra pull request #15
Opened 2022-12-29 20:43 UTC by jonapap

2022-12-31 17:53 UTC, NoahSprenger approved these changes

2022-12-31 18:03 UTC, MarwanMashaly1 approved these changes

2022-12-31 20:11 UTC, ajayyy requested changes

2022-12-31 20:11 UTC, ajayyy commented on README.md
> +This project is licensed under GPLv3.
```suggestion
This project is licensed under GPLv3-only.
```

2023-01-02 00:46 UTC, ajayyy commented on README.md
> +This project is licensed under GPLv3-only.
If you are curious, this is opposed to `GPLv3-or-any-later-version` (if FSF releases a GPL 4, which probably won't happen)

2023-01-02 00:46 UTC, ajayyy approved these changes

2023-01-02 00:46 UTC, merged